version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:5002"
    volumes:
      - nginx_data:/user/asus/desktop
    networks:
      - my_network
    environment:
      - NGINX_PORT=80
  
  alpine:
    image: alpine:latest
    container_name: alpine_container
    ports:
      - "3000:8000"
    volumes:
      - alpine_data:/user/asus/desktop
    networks:
      - my_network
    environment:
      - ALPINE_PORT=30
    
volumes:
  nginx_data:
  alpine_data:

networks:
  my_network:
    driver: bridge